### ISSUE TITLE
Lita Stops After Running For Days

### ISSUE THREAD

**Issue by MattMencel** [jimmycuadra/lita#94]
So I've just been restarting the lita service when this happens as it's only been a small annoyance to this point, but the lita service will run for days and then it just stops responding to commands from my HipChat account.  This is the log entry from the last time it stopped.

```
D, [2015-04-01T20:43:54.358358 #3075] DEBUG -- : SENDING:

W, [2015-04-01T20:44:28.655955 #3075]  WARN -- : EXCEPTION:
    Errno::ECONNRESET
    Connection reset by peer
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:45:in `sysread'
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:45:in `sysread'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/openssl/buffering.rb:61:in `fill_rbuff'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/openssl/buffering.rb:301:in `eof?'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/source.rb:235:in `empty?'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:148:in `empty?'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:196:in `pull_event'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:184:in `pull'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/sax2parser.rb:92:in `parse'
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:91:in `parse'
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75:in `block in start'
W, [2015-04-01T20:44:28.656279 #3075]  WARN -- : Exception caught in Parser thread! (Errno::ECONNRESET)
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:45:in `sysread'
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:45:in `sysread'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/openssl/buffering.rb:61:in `fill_rbuff'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/openssl/buffering.rb:301:in `eof?'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/source.rb:235:in `empty?'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:148:in `empty?'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:196:in `pull_event'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:184:in `pull'
    /opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/sax2parser.rb:92:in `parse'
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:91:in `parse'
    /opt/lita/vendor/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75:in `block in start'
```

Lita is running...
```
# service lita status
* lita is running
```
Just doesn't respond to commands.

**Comment by jimmycuadra** [comment]
I just released [lita-hipchat v2.1.2](https://github.com/jimmycuadra/lita-hipchat/releases/tag/v2.1.2) which should fix this. Please reopen this (or open an issue on that project) if it doesn't! Thanks for the report.
